#cloud-config
package_upgrade: true
packages:
  - awscli
  - git
  - nginx
  - uwsgi
  - uwsgi-plugin-python3
  - python3-flask
  - python3-flask-sqlalchemy
  - python3-flaskext.wtf
  - python3-psycopg2

users:
- default
- name: my_user
  groups: admin
  shell: /bin/bash
  ssh-authorized-keys:
  - ssh-rsa <my_user_rsa_public_key>

runcmd:
- ["git", "clone", "--single-branch", "--depth=1", "https://github.com/amaciel81/survey.git", "/tmp/survey"]
- ["mv", "/tmp/survey/app", "/var/www/survey/"]
- ["chown", "-r", "www-data:www-data", "/var/www/survey/"]
- ["mv", "/tmp/survey/nginx/survey", "/etc/nginx/sites-available/survey"]
- ["ln", "-s", "/etc/nginx/sites-available/survey", "/etc/nginx/sites-enabled/survey"]
- ["rm", "/etc/nginx/sites-enabled/default"]
- ["mv", "/tmp/survey/uwsgi/survey.ini", "/etc/uwsgi/apps-available/survey.ini"]
- ["ln", "-s", "/etc/uwsgi/apps-available/survey.ini", "/etc/uwsgi/apps-enabled/survey.ini"]
- ["rm", "-fr", "/tmp/survey"]
- ["sh", "-c", "aws s3 --quiet cp s3://<my_secret_bucket>/survey/secrets - >> /etc/uwsgi/apps-available/survey.ini"]
- ["systemctl", "restart", "uwsgi"]
- ["systemctl", "restart", "nginx"]